### ISSUE TITLE
Top menu does not always switch to mobile mode

### ISSUE THREAD

**Issue by courtiol** [holtzy/data_to_viz#1]
On my iPad the top menu remains in desktop mode so all titles are overlapping. Will have to check if my browser is not out of date, but double check. Since conference people may have iPads, it may be worth fixing before release.
++

**Comment by courtiol** [comment]
Note: it only happens in landscape mode, otherwise the mobile menu kicks in!
I have iOS 9.3.5 on the Ipad retina and the browser is Safari 9.
It is pretty old but I cannot update on this old iPad, so perhaps it works smoothly on more recent ones...

**Comment by holtzy** [comment]
Thanks for this feedback @courtiol,  I'm gonna double check.

**Comment by holtzy** [comment]
Back on this project. It looks to work properly on my iphone so I'm closing it for now. Thanks again for the feedback.
