### ISSUE TITLE
Overplotting page crashes in firefox

### ISSUE THREAD

**Issue by hwalinga** [holtzy/data_to_viz#15]
Hey, I have been browsing your cool website, but this page crashes in Firefox (consistently):

https://www.data-to-viz.com/caveat/overplotting.html

It might be those huge embedded images that cause this. It works fine in Chrome, though.

I am using Firefox 60 on Linux Mint.

Edit:  
I suddenly see that there is also a cool interactive 3D plot in there. Might be the issue as well, since other pages work fine. Maybe disable that one by default (if it really is the issue), and load in on demand? So that the content is also visible for those that do not think of using another browser.

**Comment by holtzy** [comment]
Thx for the feedback. I'm finally back on this project. I've just checked and the page diid not break for me, so I'll leave it as-is for now. Thx again! 🙏

**Comment by hwalinga** [comment]
Thanks for coming back! Yes, works fine on my side too now. Guess Firefox has improved over the years.
