### ISSUE TITLE
Python examples

### ISSUE THREAD

**Issue by sedaboni** [holtzy/data_to_viz#16]
Hello,
I would like to help the project adding a section of Python examples. Is it possible or should I fork?

**Comment by holtzy** [comment]
Hi Sedaboni,

Thx for your interest! Unfortunately, the Python graph gallery that provides the python example is built in Wordpress and thus do not allow pull request..

If you want to add example, please send me an e-mail with its potential content.

Everything is explained here:
https://github.com/holtzy/The-Python-Graph-Gallery

Thanks again!

Yan
