### ISSUE TITLE
Awesome site

### ISSUE THREAD

**Issue by mcSamuelDataSci** [holtzy/data_to_viz#20]
This isn't really a GitHub issue, but 1) I just want to say how incredible this site is, and how useful it will be for me in my own work, and for some lectures I give on visual display; and 2) there are quite a few minor and unimportant grammatical errors in English--if there was any reason to fix these, I would be happy to assist, if there was some convenient file I could edit and send back to you?

**Comment by holtzy** [comment]
Hi Michael,

Thank you very much for your message, much appreciated. I'm not a native English Speaker, what explains all the English mistakes in the website..

It would be awesome to get help on that! If you feel like making some correction, you can: 

- fork the whole repo
- edit any `.rmd` file in the repo. Don't edit any `.html file`, they are built from the `.rmd`.
- make a pull request. 

I will accept it and re build the website with the correction.

Thanks so much for your interest and please tell me if this makes sense to you!
