### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by mjkozicki** [holtzy/data_to_viz#30]
Please add a LICENSE file to define terms of use. Thanks!

**Comment by firasm** [comment]
Hey there +1 for license and terms of use.

I'd like to use some of the material here (with attribution of course) in a course I'm teaching this fall.

**Comment by holtzy** [comment]
Hi @mjkozicki and @firasm,
I've just added a MIT license to the project.
Please feel free to use the project as much as you want, but please cite it and link to it to make it grow!
Also, there is a poster for sale :)
