### ISSUE TITLE
Adding title on Sankey (while using R)

### ISSUE THREAD

**Issue by thap2331** [holtzy/data_to_viz#35]
Thank you for data to viz website. I am learning Sankey diagram. On this web page :  https://www.data-to-viz.com/graph/sankey.html  , how can I add title to the first plot? I want to use R as done in this web page. Thanks a lot in advance.

**Comment by holtzy** [comment]
Hi, I'm sorry but I do not provide 1 to 1 help in github issues, I'm just trying to correct what's wrong in the website here. Sorry for the inconvenience!
