### ISSUE TITLE
Put URL in repo description?

### ISSUE THREAD

**Issue by maelle** [holtzy/data_to_viz#4]
I mean at the top near "Leading to the dataviz you need "

**Comment by holtzy** [comment]
Hi Maëlle, thanks for that, I will do once the site will be announced (in 2 weeks)

**Comment by maelle** [comment]
👍 note that the URL is in the README (I refrained from starring the repo 👼 )

**Comment by holtzy** [comment]
Read me is now done. Links added. Thx Maëlle.
